# Lab | Data Aggregation and Filtering

In this challenge, we will continue to work with customer data from an insurance company. We will use the dataset called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by first performing data cleaning, formatting, and structuring.

In [33]:
import pandas as pd
marketing_df = pd.read_csv('https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv')
display(marketing_df.columns)

#Clean column names
def normalize_titles(col):
    return col.strip().lower().replace(' ','_')
marketing_df.columns=marketing_df.columns.map(normalize_titles)
#drop unnecesary column:
marketing_df = marketing_df.drop(columns=["unnamed:_0"])
#Rename column for employment status:
marketing_df = marketing_df.rename(columns={"employmentstatus": "employment_status"})
print(marketing_df.columns)
display(marketing_df.head())
display(marketing_df.vehicle_type)
display(marketing_df.state.value_counts().value_counts())
display(marketing_df.response.value_counts())
display(marketing_df.coverage.value_counts())
display(marketing_df.education.value_counts())
display(marketing_df.employment_status.value_counts())
display(marketing_df.gender.value_counts())
display(marketing_df.isna().sum())
display(marketing_df.dtypes)
display(marketing_df.shape)
marketing_df.duplicated().sum()

Index(['Unnamed: 0', 'Customer', 'State', 'Customer Lifetime Value',
       'Response', 'Coverage', 'Education', 'Effective To Date',
       'EmploymentStatus', 'Gender', 'Income', 'Location Code',
       'Marital Status', 'Monthly Premium Auto', 'Months Since Last Claim',
       'Months Since Policy Inception', 'Number of Open Complaints',
       'Number of Policies', 'Policy Type', 'Policy', 'Renew Offer Type',
       'Sales Channel', 'Total Claim Amount', 'Vehicle Class', 'Vehicle Size',
       'Vehicle Type'],
      dtype='str')

Index(['customer', 'state', 'customer_lifetime_value', 'response', 'coverage',
       'education', 'effective_to_date', 'employment_status', 'gender',
       'income', 'location_code', 'marital_status', 'monthly_premium_auto',
       'months_since_last_claim', 'months_since_policy_inception',
       'number_of_open_complaints', 'number_of_policies', 'policy_type',
       'policy', 'renew_offer_type', 'sales_channel', 'total_claim_amount',
       'vehicle_class', 'vehicle_size', 'vehicle_type'],
      dtype='str')

,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employment_status,gender,income,...,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
0,DK49336,Arizona,4809.216960,No,Basic,College,2/18/11,Employed,M,48029,...,0.0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,KX64629,California,2228.525238,No,Basic,College,1/18/11,Unemployed,F,0,...,0.0,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2/10/11,Employed,M,22139,...,0.0,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,49078,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,1/17/11,Medical Leave,F,23675,...,NaN,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN

0        NaN
1        NaN
2          A
3          A
4        NaN
        ...
10905      A
10906      A
10907    NaN
10908      A
10909    NaN
Name: vehicle_type, Length: 10910, dtype: str

count
3552    1
2909    1
1937    1
993     1
888     1
Name: count, dtype: int64

response
No     8813
Yes    1466
Name: count, dtype: int64

coverage
Basic       6660
Extended    3265
Premium      985
Name: count, dtype: int64

education
Bachelor                3272
College                 3204
High School or Below    3146
Master                   887
Doctor                   401
Name: count, dtype: int64

employment_status
Employed         6789
Unemployed       2787
Medical Leave     504
Disabled          499
Retired           331
Name: count, dtype: int64

gender
F    5573
M    5337
Name: count, dtype: int64

customer                            0
state                             631
customer_lifetime_value             0
response                          631
coverage                            0
education                           0
effective_to_date                   0
employment_status                   0
gender                              0
income                              0
location_code                       0
marital_status                      0
monthly_premium_auto                0
months_since_last_claim           633
months_since_policy_inception       0
number_of_open_complaints         633
number_of_policies                  0
policy_type                         0
policy                              0
renew_offer_type                    0
sales_channel                       0
total_claim_amount                  0
vehicle_class                     622
vehicle_size                      622
vehicle_type                     5482
dtype: int64

customer                             str
state                                str
customer_lifetime_value          float64
response                             str
coverage                             str
education                            str
effective_to_date                    str
employment_status                    str
gender                               str
income                             int64
location_code                        str
marital_status                       str
monthly_premium_auto               int64
months_since_last_claim          float64
months_since_policy_inception      int64
number_of_open_complaints        float64
number_of_policies                 int64
policy_type                          str
policy                               str
renew_offer_type                     str
sales_channel                        str
total_claim_amount               float64
vehicle_class                        str
vehicle_size                         str
vehicle_type                         str
dtype: object

(10910, 25)

np.int64(37)

In [34]:
# Drop duplicated values:
marketing_df = marketing_df.drop_duplicates().reset_index(drop=True)
# Fill categorical columns with null values with unknown:
marketing_df["state"] = marketing_df["state"].fillna("Unknown")
marketing_df["response"] = marketing_df["response"].fillna("Unknown")
marketing_df["vehicle_class"] = marketing_df["vehicle_class"].fillna("Unknown")
marketing_df["vehicle_size"] = marketing_df["vehicle_size"].fillna("Unknown")
# Drop column with too many missing values to be useful (5482 null values out of 10910 rows):
marketing_df = marketing_df.drop(columns=["vehicle_type"])

In [35]:
#See how many null values are still missing and if they all concentrate in the same rows:
display(marketing_df.isna().sum())

rows_with_nulls = marketing_df[marketing_df.isna().any(axis=1)]
display(rows_with_nulls.shape)
display(rows_with_nulls.head())
display(rows_with_nulls.isna().sum(axis=1).value_counts())

display(marketing_df.shape)

customer                           0
state                              0
customer_lifetime_value            0
response                           0
coverage                           0
education                          0
effective_to_date                  0
employment_status                  0
gender                             0
income                             0
location_code                      0
marital_status                     0
monthly_premium_auto               0
months_since_last_claim          623
months_since_policy_inception      0
number_of_open_complaints        623
number_of_policies                 0
policy_type                        0
policy                             0
renew_offer_type                   0
sales_channel                      0
total_claim_amount                 0
vehicle_class                      0
vehicle_size                       0
dtype: int64

(623, 24)

,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employment_status,gender,income,...,months_since_policy_inception,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size
4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,1/17/11,Medical Leave,F,23675,...,31,NaN,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize
23,NQ71171,California,5107.071054,No,Basic,Bachelor,2/2/11,Employed,M,70174,...,80,NaN,7,Personal Auto,Personal L2,Offer1,Agent,128.900320,Four-Door Car,Medsize
51,FT56968,Arizona,2590.096027,No,Basic,High School or Below,1/3/11,Employed,M,22398,...,76,NaN,1,Personal Auto,Personal L1,Offer1,Agent,321.600000,Four-Door Car,Large
59,EP83939,Arizona,5575.751228,No,Basic,High School or Below,1/26/11,Employed,M,91416,...,39,NaN,5,Personal Auto,Personal L3,Offer2,Call Center,109.904496,Four-Door Car,Medsize
67,KR35099,Washington,7507.455372,Yes,Basic,College,2/6/11,Employed,M,60920,...,61,NaN,2,Personal Auto,Personal L3,Offer2,Agent,231.201886,Two-Door Car,Medsize

2    623
Name: count, dtype: int64

(10873, 24)

In [40]:
#Fill missing values in number of open complaints as 0 and months since the last claim with the median and convert to the integers:
marketing_df["number_of_open_complaints"] = marketing_df["number_of_open_complaints"].fillna(0)
# I used the median instead of the mean because it is less affected by extreme values
marketing_df["months_since_last_claim"] = marketing_df["months_since_last_claim"].fillna(marketing_df["months_since_last_claim"].median())
marketing_df["number_of_open_complaints"] = marketing_df["number_of_open_complaints"].astype(int)
marketing_df["months_since_last_claim"] = marketing_df["months_since_last_claim"].astype(int)
display(marketing_df.number_of_open_complaints.value_counts())
display(marketing_df.months_since_last_claim.value_counts())
display(marketing_df.months_since_last_claim.median())
display(marketing_df.months_since_last_claim.mean())

number_of_open_complaints
0    8764
1    1141
2     414
3     321
4     166
5      67
Name: count, dtype: int64

months_since_last_claim
14    920
3     426
6     394
1     386
7     377
4     372
2     365
5     354
0     353
10    345
16    333
11    331
15    323
13    320
8     315
12    306
17    298
19    275
9     275
23    273
25    269
21    267
18    257
20    254
22    245
24    236
29    233
28    225
31    219
26    211
27    207
30    201
34    199
33    198
35    156
32    155
Name: count, dtype: int64

np.float64(14.0)

np.float64(15.079462889726846)

In [41]:
# Checking there are no more null values and that all the variables are the appropiate type:
display(marketing_df.isna().sum())
display(marketing_df.dtypes)

customer                         0
state                            0
customer_lifetime_value          0
response                         0
coverage                         0
education                        0
effective_to_date                0
employment_status                0
gender                           0
income                           0
location_code                    0
marital_status                   0
monthly_premium_auto             0
months_since_last_claim          0
months_since_policy_inception    0
number_of_open_complaints        0
number_of_policies               0
policy_type                      0
policy                           0
renew_offer_type                 0
sales_channel                    0
total_claim_amount               0
vehicle_class                    0
vehicle_size                     0
dtype: int64

customer                             str
state                                str
customer_lifetime_value          float64
response                             str
coverage                             str
education                            str
effective_to_date                    str
employment_status                    str
gender                               str
income                             int64
location_code                        str
marital_status                       str
monthly_premium_auto               int64
months_since_last_claim            int64
months_since_policy_inception      int64
number_of_open_complaints          int64
number_of_policies                 int64
policy_type                          str
policy                               str
renew_offer_type                     str
sales_channel                        str
total_claim_amount               float64
vehicle_class                        str
vehicle_size                         str
dtype: object

1. Create a new DataFrame that only includes customers who:
   - have a **low total_claim_amount** (e.g., below $1,000),
   - have a response "Yes" to the last marketing campaign.

In [44]:
# Making new filtered data frame and checking its shape:
marketing_df["total_claim_amount"] = marketing_df["total_claim_amount"].round(2)
low_claim_yes_response = marketing_df[(marketing_df["total_claim_amount"] < 1000) &(marketing_df["response"] == "Yes")]
display(low_claim_yes_response)
display(low_claim_yes_response.shape)
display(low_claim_yes_response[["total_claim_amount", "response"]].head())
display(low_claim_yes_response["response"].value_counts())
display(low_claim_yes_response["total_claim_amount"].describe())

,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employment_status,gender,income,...,months_since_policy_inception,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size
3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,49078,...,3,0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.01,Four-Door Car,Medsize
8,FM55990,California,5989.773931,Yes,Premium,College,1/19/11,Employed,M,66839,...,24,0,1,Personal Auto,Personal L1,Offer2,Branch,739.20,Sports Car,Medsize
15,CW49887,California,4626.801093,Yes,Basic,Master,1/16/11,Employed,F,79487,...,87,0,1,Special Auto,Special L1,Offer2,Branch,547.20,SUV,Medsize
19,NJ54277,California,3746.751625,Yes,Extended,College,2/26/11,Employed,F,41479,...,38,1,1,Personal Auto,Personal L2,Offer2,Call Center,19.58,Two-Door Car,Large
27,MQ68407,Oregon,4376.363592,Yes,Premium,Bachelor,2/28/11,Employed,F,63774,...,63,0,1,Personal Auto,Personal L3,Offer2,Agent,60.04,Four-Door Car,Medsize
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10807,FM31768,Arizona,5979.724161,Yes,Extended,High School or Below,2/7/11,Employed,F,57693,...,56,0,3,Personal Auto,Personal L1,Offer2,Agent,547.20,Four-Door Car,Medsize
10815,KZ80424,Washington,8382.478392,Yes,Basic,Bachelor,1/27/11,Employed,M,25998,...,38,0,2,Personal Auto,Personal L2,Offer2,Call Center,791.88,Unknown,Unknown
10835,XT67997,California,5979.724161,Yes,Extended,High School or Below,2/7/11,Employed,F,57693,...,56,0,3,Personal Auto,Personal L3,Offer2,Agent,547.20,Four-Door Car,Medsize
10850,BY78730,Oregon,8879.790017,Yes,Basic,High School or Below,2/3/11,Employed,F,52583,...,59,0,7,Special Auto,Special L2,Offer1,Agent,528.20,SUV,Small
10860,MM70762,Arizona,9075.768214,Yes,Basic,Master,1/26/11,Employed,M,37722,...,23,0,8,Personal Auto,Personal L1,Offer1,Agent,158.08,Sports Car,Medsize

(1397, 24)

    total_claim_amount response
3               484.01      Yes
8               739.20      Yes
15              547.20      Yes
19               19.58      Yes
27               60.04      Yes

response
Yes    1397
Name: count, dtype: int64

count    1397.000000
mean      411.943729
std       180.518055
min         7.350000
25%       312.000000
50%       398.500000
75%       528.200000
max       960.120000
Name: total_claim_amount, dtype: float64

2. Using the original Dataframe, analyze:
   - the average `monthly_premium` and/or customer lifetime value by `policy_type` and `gender` for customers who responded "Yes", and
   - compare these insights to `total_claim_amount` patterns, and discuss which segments appear most profitable or low-risk for the company.

In [46]:
yes_customers = marketing_df[marketing_df["response"] == "Yes"]
segment_analysis = yes_customers.groupby(["policy_type", "gender"])[["monthly_premium_auto","customer_lifetime_value","total_claim_amount"]].mean().round(2)
display(segment_analysis)
#In the group of customers who responded "Yes", the most profitable-looking segment is Personal Auto - F because it has the highest average customer lifetime value and the highest monthly premium. However, it also has a relatively high average total claim amount.
#Corporate Auto - M also looks attractive because it has a high customer lifetime value and the lowest average total claim amount. This makes it a lower-risk segment.
#Special Auto - M has a strong customer lifetime value and a low total claim amount, but its monthly premium is the lowest, so it may be valuable but brings in less monthly revenue.
#Personal Auto - M appears less profitable because it has the lowest customer lifetime value and the highest total claim amount.

                       monthly_premium_auto  customer_lifetime_value  \
policy_type    gender
Corporate Auto F                      94.30                  7712.63
               M                      92.13                  7928.36
Personal Auto  F                      98.96                  8339.10
               M                      91.09                  7448.38
Special Auto   F                      92.31                  7691.58
               M                      86.34                  8247.09

                       total_claim_amount
policy_type    gender
Corporate Auto F                   433.74
               M                   407.83
Personal Auto  F                   452.76
               M                   457.01
Special Auto   F                   453.28
               M                   429.53

3. Analyze the total number of customers who have policies in each state, and then filter the results to only include states where there are more than 500 customers.

In [55]:
customers_by_state = marketing_df.groupby("state")[["customer"]].count()
display(customers_by_state)
high_customers_state = customers_by_state[customers_by_state["customer"] > 500]
display(high_customers_state)
#California has the highest number of customers, followed by Oregon and Arizona. Nevada and Washington also have more than 500 customers, but smaller customer bases. The `Unknown` category has 614 customers, which means there are still many records where the state was missing.

            customer
state
Arizona         1934
California      3548
Nevada           992
Oregon          2897
Unknown          614
Washington       888

            customer
state
Arizona         1934
California      3548
Nevada           992
Oregon          2897
Unknown          614
Washington       888

4. Find the maximum, minimum, and median customer lifetime value by education level and gender. Write your conclusions.

In [56]:
clf_education_gender = yes_customers.groupby(["education", "gender"])[["customer_lifetime_value"]].agg(['max', 'median', 'min'])
display(clf_education_gender)
#Customer lifetime value varies by education level and gender. 
#The highest maximum value appears for females with High School or Below education, followed by females with a Bachelor degree. 
#Looking at the median, males with a Master degree have the highest typical customer lifetime value, while females with a Doctor degree have the lowest median value.
#Overall, education level seems to show more differences than gender, especially when comparing median customer lifetime value across groups.

                            customer_lifetime_value
                                                max       median          min
education            gender
Bachelor             F                 33473.349460  5246.278375  2248.449633
                     M                 24127.504020  5548.031892  2300.691547
College              F                 25807.063000  4834.710493  2004.350666
                     M                 22332.439460  5989.773931  2393.915369
Doctor               F                  6265.343299  4673.457903  2395.570000
                     M                 12731.951610  5073.282126  2491.317024
High School or Below F                 41787.903430  6503.397049  2397.036098
                     M                 12298.686300  6366.225775  2227.072755
Master               F                 19160.989940  5096.673223  2574.020376
                     M                 14435.673650  8509.850887  2551.226692

## Bonus

5. The marketing team wants to analyze the number of policies sold by state and month. Present the data in a table where the months are arranged as columns and the states are arranged as rows.

In [60]:
#there is no month column so it must be extracted from the date column:
marketing_df["effective_to_date"] = pd.to_datetime(marketing_df["effective_to_date"], format="%m/%d/%y")
marketing_df["month"] = marketing_df["effective_to_date"].dt.month

policies_state_month = marketing_df.pivot_table(index="state",columns="month",values="number_of_policies",aggfunc="sum")
display(policies_state_month)

month          1     2
state
Arizona     3050  2853
California  5669  4927
Nevada      1493  1271
Oregon      4659  3959
Unknown      962   948
Washington  1358  1225

6.  Display a new DataFrame that contains the number of policies sold by month, by state, for the top 3 states with the highest number of policies sold.

*Hint:*
- *To accomplish this, you will first need to group the data by state and month, then count the number of policies sold for each group. Afterwards, you will need to sort the data by the count of policies sold in descending order.*
- *Next, you will select the top 3 states with the highest number of policies sold.*
- *Finally, you will create a new DataFrame that contains the number of policies sold by month for each of the top 3 states.*

In [62]:
policies_by_state_month = marketing_df.groupby(["state", "month"])[["number_of_policies"]].sum().reset_index()
display(policies_by_state_month)
top_3_states = marketing_df.groupby("state")["number_of_policies"].sum().sort_values(ascending=False).head(3)
display(top_3_states)
top_3_state_names = top_3_states.index
top_3_state_month = policies_by_state_month[policies_by_state_month["state"].isin(top_3_state_names)]
display(top_3_state_month)

         state  month  number_of_policies
0      Arizona      1                3050
1      Arizona      2                2853
2   California      1                5669
3   California      2                4927
4       Nevada      1                1493
5       Nevada      2                1271
6       Oregon      1                4659
7       Oregon      2                3959
8      Unknown      1                 962
9      Unknown      2                 948
10  Washington      1                1358
11  Washington      2                1225

state
California    10596
Oregon         8618
Arizona        5903
Name: number_of_policies, dtype: int64

        state  month  number_of_policies
0     Arizona      1                3050
1     Arizona      2                2853
2  California      1                5669
3  California      2                4927
6      Oregon      1                4659
7      Oregon      2                3959

7. The marketing team wants to analyze the effect of different marketing channels on the customer response rate.

Hint: You can use melt to unpivot the data and create a table that shows the customer response rate (those who responded "Yes") by marketing channel.

External Resources for Data Filtering: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

In [64]:
response_channel = marketing_df.pivot_table(index="sales_channel",columns="response",values="customer",aggfunc="count")
display(response_channel)
response_channel_long = response_channel.reset_index().melt(id_vars="sales_channel",var_name="response",value_name="number_of_customers")
display(response_channel_long)
yes_response_rate = marketing_df.groupby("sales_channel")["response"].apply(lambda x: (x == "Yes").mean() * 100).round(2).reset_index()
yes_response_rate = yes_response_rate.rename(columns={"response": "yes_response_rate"})
display(yes_response_rate)

response         No  Unknown  Yes
sales_channel
Agent          3142      228  741
Branch         2533      155  325
Call Center    1790      121  221
Web            1330      110  177

   sales_channel response  number_of_customers
0          Agent       No                 3142
1         Branch       No                 2533
2    Call Center       No                 1790
3            Web       No                 1330
4          Agent  Unknown                  228
5         Branch  Unknown                  155
6    Call Center  Unknown                  121
7            Web  Unknown                  110
8          Agent      Yes                  741
9         Branch      Yes                  325
10   Call Center      Yes                  221
11           Web      Yes                  177

  sales_channel  yes_response_rate
0         Agent              18.02
1        Branch              10.79
2   Call Center              10.37
3           Web              10.95